# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mgonon <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/08/24 06:00:42 by mgonon            #+#    #+#              #
#    Updated: 2016/08/24 06:17:44 by mgonon           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all: $(NAME)

$(NAME):
		gcc -Werror -Wall -Wextra -o $(NAME) main.c

clean:
		rm -f $(NAME)

fclean: clean

re: fclean all

